image: maven:3.8.1-jdk-11

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn test-compile compile
  tags:
    - gitlab-org-docker

test:
  stage: test
  script:
    - mvn verify
  tags:
    - gitlab-org-docker